typography_spectrum: 0.13947
color:
  brandColors:
    - '#727a7d'
    - '#c3beb8'
    - '#322b21'
    - '#070a00'
    - '#554835'
  brandStrength: 0.8125
  lightness: 0.49081995990127325
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53095
analytics:
  google: null
  facebook: null
  twitter: null
name: laughingchance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: f8a1cc64-4115-4dbc-9a97-13e0fcea6c7b
    type: content
favicon: null
purpose: []
