typography_spectrum: 0.874162386637181
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.3302691837307066
  lightness: 0.8504825746640563
  saturation: 0.22950401925481856
  rhythmicContrast: 0.978120538406074
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7693311059847474
analytics:
  google: null
  facebook: null
  twitter: null
name: laughingchance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: f8a1cc64-4115-4dbc-9a97-13e0fcea6c7b
    type: content
  - name: Pictures
    id: 1d417a88-5f95-4c92-894b-4fb4727b33d7
    type: content
favicon: null
purpose: []
