name: laughingchance
favicon: null
layout_spectrum: 0.53095
typography_spectrum: 0.13947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#727a7d'
    - '#c3beb8'
    - '#322b21'
    - '#070a00'
    - '#554835'
  brandStrength: 0.8125
  lightness: 0.49081995990127325
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
